remote_theme: pages-themes/minimal@v0.2.0
title: Deyaa Mohammed
logo: /assets/img/me.png
description: <h4>Tech enthusiast, software tester, and avid gamer. Driven by a passion for technology and a commitment to delivering exceptional software solutions.<h4> <h4><a href= "https://deyaamohammed.github.io">Home</a> - <a href = "/projects">Projects</a> - <a href = "/learningjourney">Learning Journey</a></h4>
show_downloads: false
